require 'time_spanner/time_units/time_unit_collection'
require 'time_spanner/time_units/time_unit'
require 'time_spanner/time_units/hours'
require 'time_spanner/time_units/minutes'
require 'time_spanner/time_units/nanosecond'