require 'time_spanner/time_units/time_unit'
require 'time_spanner/time_units/hour'
require 'time_spanner/time_units/minute'
require 'time_spanner/time_units/nanosecond'
require 'time_spanner/time_units/microsecond'
require 'time_spanner/time_units/time_unit_collection'